name: Build the Extension

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [published]
  pull_request:
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: calculate version
        run: |
          version="$(git describe --tags)"
          stripped_version="${version#v}"
          echo $stripped_version
          echo "version=${stripped_version}" >> $GITHUB_ENV
      - name: Package prerelease vsix
        if:  github.event_name != 'release' || github.event.release.prerelease
        run: npx vsce package --no-git-tag-version --pre-release ${{ env.version }}
      - name: Package vsix
        if: github.event_name == 'release' && !(github.event.release.prerelease)
        run: npx vsce package --no-git-tag-version ${{ env.version }}
      - name: Upload package
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: pydjinni-vscode-${{ env.version }}
          path: pydjinni-vscode-${{ env.version }}.vsix
      - name: Publish package
        if: github.event_name == 'release'
        run: npx vsce publish --packagePath pydjinni-vscode-${{ env.version }}.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
